# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_bin
  reconnect: false

development:
  <<: *default
  database: <%= Rails.application.secrets[:database][:name] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  host: <%= Rails.application.secrets[:database][:host] %>
  port: <%= Rails.application.secrets[:database][:port] %>

test:
  <<: *default
  database: <%= Rails.application.secrets[:database][:name] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  host: <%= Rails.application.secrets[:database][:host] %>
  port: <%= Rails.application.secrets[:database][:port] %>

production:
  <<: *default
  host: <%= ENV['THESIS-APP_DATABASE_HOST'] %>
  database: <%= ENV['THESIS-APP_DATABASE_HOST'] %>
  username: <%= ENV['THESIS-APP_DATABASE_HOST'] %>
  password: <%= ENV['THESIS-APP_DATABASE_PASSWORD'] %>